import { computed } from 'vue';
import { buildRecordActivityUi } from '@/components/activity/useRecordActivityAdapter';

export const createDealActivityUi = ({
  authStore,
  expandedTaskEmailThreads,
  editingNoteId,
  editingNoteText,
  editingNoteAttachments,
  isEditingCommentDirty,
  setEditingCommentText,
  setEditingCommentAttachments,
  handleEditCommentFilesChange,
  saveEditedNote,
  handleSaveEditCommentClick,
  cancelEditNote,
  canEditNote,
  startEditNote,
  getInitials,
  getAuthorName,
  formatFullTimestamp,
  formatRelativeActivityTime,
  handleTimestampPointerUp,
  highlightSearchText,
  commentMentionsCurrentUser,
  hasAttachmentUrl,
  getAttachmentUrl,
  isImageAttachment,
  isSvgAttachment,
  getAttachmentName,
  downloadAttachment,
  formatFileSize,
  getAttachmentLabel,
  hasCommentReactions,
  getCommentReactions,
  isCommentReactionSelected,
  toggleCommentReaction,
  handleShowCommentReactionTooltip,
  handleHideCommentReactionTooltip,
  setCommentReactionButtonRef,
  toggleCommentReactionPicker,
  openCommentThread,
  getCommentThreadReplyCount,
  getCommentThreadLatestReplyAuthor,
  isFieldChangeSystemEvent,
  getSystemEventActorLabel,
  getSystemEventFieldLabel,
  getSystemEventFromValue,
  getSystemEventToValue,
  getSystemEventMessage,
  handleShowMore,
  toggleTaskEmailThread,
  createTaskFromEmailMessage,
  getTagChipClass
}) => computed(() => buildRecordActivityUi({
  currentUser: authStore.user || null,
  expandedTaskEmailThreads: expandedTaskEmailThreads.value,

  editingCommentId: editingNoteId.value,
  editingCommentText: editingNoteText.value,
  editingCommentAttachments: editingNoteAttachments.value,
  isEditingCommentDirty: isEditingCommentDirty.value,

  setEditingCommentText,
  setEditingCommentAttachments,
  handleEditCommentFilesChange,
  saveEditComment: saveEditedNote,
  handleSaveEditCommentClick,
  cancelEditComment: cancelEditNote,
  canEditComment: canEditNote,
  startEditComment: startEditNote,

  getInitials,
  getAuthorName,
  formatFullTimestamp,
  formatRelativeActivityTime,
  handleTimestampPointerUp,
  highlightSearchText,
  commentMentionsCurrentUser,

  hasAttachmentUrl,
  getAttachmentUrl,
  isImageAttachment,
  isSvgAttachment,
  getAttachmentName,
  downloadAttachment,
  formatFileSize,
  getAttachmentLabel,

  hasCommentReactions,
  getCommentReactions,
  isCommentReactionSelected,
  toggleCommentReaction,
  handleShowCommentReactionTooltip,
  handleHideCommentReactionTooltip,
  setCommentReactionButtonRef,
  toggleCommentReactionPicker,

  openCommentThread,
  getCommentThreadReplyCount,
  getCommentThreadLatestReplyAuthor,

  isFieldChangeSystemEvent,
  getSystemEventActorLabel,
  getSystemEventFieldLabel,
  getSystemEventFromValue,
  getSystemEventToValue,
  getSystemEventMessage,
  handleShowMore,

  toggleTaskEmailThread,
  createTaskFromEmailMessage,
  getTagChipClass
}));
