import { computed } from 'vue';
import { buildRecordActivityUi } from '@/components/activity/useRecordActivityAdapter';

export const createTaskActivityUi = ({
  authStore,
  expandedTaskEmailThreads,
  editingCommentId,
  editingCommentText,
  editingCommentAttachments,
  isEditingCommentDirty,
  setEditingCommentText,
  setEditingCommentAttachments,
  handleEditCommentFilesChange,
  saveEditComment,
  handleSaveEditCommentClick,
  cancelEditComment,
  canEditComment,
  startEditComment,
  getInitials,
  getAuthorName,
  formatFullTimestamp,
  formatRelativeActivityTime,
  handleTimestampPointerUp,
  highlightSearchText,
  commentMentionsCurrentUser,
  hasAttachmentUrl,
  getAttachmentUrl,
  isImageAttachment,
  isSvgAttachment,
  getAttachmentName,
  downloadAttachment,
  formatFileSize,
  getAttachmentLabel,
  hasCommentReactions,
  getCommentReactions,
  isCommentReactionSelected,
  toggleCommentReaction,
  handleShowCommentReactionTooltip,
  handleHideCommentReactionTooltip,
  setCommentReactionButtonRef,
  toggleCommentReactionPicker,
  openCommentThread,
  getCommentThreadReplyCount,
  getCommentThreadLatestReplyAuthor,
  isFieldChangeSystemEvent,
  getSystemEventActorLabel,
  getSystemEventFieldLabel,
  getSystemEventFromValue,
  getSystemEventToValue,
  getSystemEventMessage,
  handleShowMore,
  toggleTaskEmailThread,
  createTaskFromEmailMessage
}) => computed(() => buildRecordActivityUi({
  currentUser: authStore.user || null,
  expandedTaskEmailThreads: expandedTaskEmailThreads.value,
  editingCommentId: editingCommentId.value,
  editingCommentText: editingCommentText.value,
  editingCommentAttachments: editingCommentAttachments.value,
  isEditingCommentDirty: isEditingCommentDirty.value,

  setEditingCommentText,
  setEditingCommentAttachments,
  handleEditCommentFilesChange,
  saveEditComment,
  handleSaveEditCommentClick,
  cancelEditComment,
  canEditComment,
  startEditComment,

  getInitials,
  getAuthorName,
  formatFullTimestamp,
  formatRelativeActivityTime,
  handleTimestampPointerUp,
  highlightSearchText,
  commentMentionsCurrentUser,

  hasAttachmentUrl,
  getAttachmentUrl,
  isImageAttachment,
  isSvgAttachment,
  getAttachmentName,
  downloadAttachment,
  formatFileSize,
  getAttachmentLabel,

  hasCommentReactions,
  getCommentReactions,
  isCommentReactionSelected,
  toggleCommentReaction,
  handleShowCommentReactionTooltip,
  handleHideCommentReactionTooltip,
  setCommentReactionButtonRef,
  toggleCommentReactionPicker,

  openCommentThread,
  getCommentThreadReplyCount,
  getCommentThreadLatestReplyAuthor,

  isFieldChangeSystemEvent,
  getSystemEventActorLabel,
  getSystemEventFieldLabel,
  getSystemEventFromValue,
  getSystemEventToValue,
  getSystemEventMessage,
  handleShowMore,

  toggleTaskEmailThread,
  createTaskFromEmailMessage
}));
