/**
 * Canonical domain event names used for notifications and system signals.
 * Channels, recipients, and delivery logic live elsewhere.
 */
module.exports = {
  // Audit events
  AUDIT_ASSIGNED: 'AUDIT_ASSIGNED',
  AUDIT_CHECKED_IN: 'AUDIT_CHECKED_IN',
  AUDIT_SUBMITTED: 'AUDIT_SUBMITTED',
  AUDIT_APPROVED: 'AUDIT_APPROVED',
  AUDIT_REJECTED: 'AUDIT_REJECTED',

  // Corrective action events
  CORRECTIVE_ACTION_CREATED: 'CORRECTIVE_ACTION_CREATED',
  CORRECTIVE_ACTION_DUE_SOON: 'CORRECTIVE_ACTION_DUE_SOON',
  CORRECTIVE_ACTION_OVERDUE: 'CORRECTIVE_ACTION_OVERDUE',

  // Task events (Phase 17: Notification Rules)
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_DUE_SOON: 'TASK_DUE_SOON',

  // Other events
  EVIDENCE_UPLOADED: 'EVIDENCE_UPLOADED',
  PORTAL_ACCOUNT_CREATED: 'PORTAL_ACCOUNT_CREATED',
  USER_ADDED_TO_APP: 'USER_ADDED_TO_APP',

  // System events
  SYSTEM_TRIAL_EXPIRING: 'SYSTEM_TRIAL_EXPIRING',
  SYSTEM_SUBSCRIPTION_SUSPENDED: 'SYSTEM_SUBSCRIPTION_SUSPENDED',

  // Digest events
  DIGEST_DAILY: 'DIGEST_DAILY',
  DIGEST_WEEKLY: 'DIGEST_WEEKLY'
};

